version: "3"


services:
  db:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: Admin123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Admin123
  node:
    image: node:18
    working_dir: /var/www/html
    tty: true
    environment:
      - YBUILD=yarn start:dev
    user: ${DOCKER_USER:-1000}:${DOCKER_USER:-1000}
    ports:
      - ${APP_PORT}:3000
      - '3003:3003'
    volumes:
      - .:/var/www/html
    command: ["bash", ".bin/build.sh"]
